version: '3'

services:
  
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./datajobs/.env
    ports:
      - 5432:5432

  django:
    build:
      context: ./datajobs
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    depends_on:
      - db
      