# Generated by Django 4.2.4 on 2023-08-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("html", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("apply_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("company_info", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
            ],
        ),
    ]
